#!/bin/bash
set -euo pipefail

ROOT="/Users/yangang/Desktop/sorry"

test -f "$ROOT/index.html"
test -f "$ROOT/style.css"
test -f "$ROOT/script.js"

grep -q 'class="single-stage"' "$ROOT/index.html"
grep -q 'class="apology-card glass-card"' "$ROOT/index.html"
grep -q 'class="tab-switcher"' "$ROOT/index.html"
grep -q 'data-tab="comfort"' "$ROOT/index.html"
grep -q 'data-tab="serious"' "$ROOT/index.html"
grep -q 'id="tab-placeholder"' "$ROOT/index.html"
grep -q 'id="tab-panel-content"' "$ROOT/index.html"
grep -q 'id="typewriter-lines"' "$ROOT/index.html"
grep -q 'id="tab-panel-title"' "$ROOT/index.html"
grep -q 'id="tab-panel-body"' "$ROOT/index.html"
grep -q 'class="kitty-sprite kitty-sprite-main"' "$ROOT/index.html"
grep -q 'class="kitty-sprite kitty-sprite-mini mini-left"' "$ROOT/index.html"
grep -q 'class="kitty-sparkles"' "$ROOT/index.html"
grep -q 'class="orbit orbit-left"' "$ROOT/index.html"
! grep -q 'kitty-sprite-trail' "$ROOT/index.html"
grep -q 'style.css' "$ROOT/index.html"
grep -q 'script.js' "$ROOT/index.html"

grep -q '.single-stage' "$ROOT/style.css"
grep -q '.apology-card' "$ROOT/style.css"
grep -q '.tab-switcher' "$ROOT/style.css"
grep -q '.tab-pill.is-active' "$ROOT/style.css"
grep -q '.tab-panel' "$ROOT/style.css"
grep -q '.tab-placeholder' "$ROOT/style.css"
grep -q '.kitty-sprite-main' "$ROOT/style.css"
grep -q '@keyframes kittyFloat' "$ROOT/style.css"
grep -q '@keyframes orbitSpin' "$ROOT/style.css"
grep -q '@keyframes spriteFrames' "$ROOT/style.css"
grep -q '@keyframes panelFade' "$ROOT/style.css"
grep -q '.kitty-sparkles' "$ROOT/style.css"

grep -q 'const playlist' "$ROOT/script.js"
grep -q 'const tabContent' "$ROOT/script.js"
grep -q 'function switchTab' "$ROOT/script.js"
grep -q 'tabPlaceholder.hidden = true' "$ROOT/script.js"
grep -q 'function tryAutoplay' "$ROOT/script.js"
grep -Fq 'const audio = playlist[0] ? new Audio(playlist[0]) : null;' "$ROOT/script.js"
